spring:
  application:
    name: Oodle Demo External
  cloud:
    consul:
      host: docker.pve.aamegremis.com
      port: 8500
      discovery:
        service-name: External API
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.service-name}
